<a href="https://colab.research.google.com/github/osurielizabethrani/AI-Lab/blob/master/experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Experiment-1:NumPy

###(i) Different ways to create NumPy arrays.

a)Create a numpy array using lists.

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


b)Create a numpy array using arange.

In [3]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [4]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

###(ii)Add,remove,modify elements in an array.

a)Add

In [5]:
b = np.append(a,[56,57,58])
b

array([ 1,  2,  3,  4, 56, 57, 58])

b)Remove

In [6]:
import numpy as np
p = np.array([9,1,3,5,6])
p = np.delete(p,4)
print(p)

[9 1 3 5]


 c)Modifying

In [7]:
a = np.array([1,2,3,4,5])
a[2] = 0
print(a)

[1 2 0 4 5]


###(iii)Arithmetic operations on NumPy arrays.

In [8]:
 
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [9]:
 
p = a+b
print(p)

[20 31 42 53]


In [10]:
c = a-b
print(c)

[20 29 38 47]


In [11]:
print(a*3)

[ 60  90 120 150]


In [12]:
print(b**2)

[0 1 4 9]


In [13]:
print(b/a)

[0.         0.03333333 0.05       0.06      ]


In [14]:
print(10*np.sin(a))

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [15]:
print(a<35)

[ True  True False False]


###(iv)Slicing and iterating of NumPy arrays.

a)Slicing

In [16]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [17]:
print(a[2])

8


In [18]:
print(a[2:4])

[ 8 27]


In [19]:
print(a[2:3])

[8]


In [20]:
a = np.arange(12).reshape(4,3)**2
print(a)

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


In [21]:
print(a[1:3])

[[ 9 16 25]
 [36 49 64]]


In [22]:
print(a[1:3,1:2])

[[16]
 [49]]


In [23]:
print(a[:2],)

[[ 0  1  4]
 [ 9 16 25]]


In [24]:
print(a[:3,:2])

[[ 0  1]
 [ 9 16]
 [36 49]]


In [25]:
print(a[:,2])

[  4  25  64 121]


Slicing using negative index.

In [26]:
 
a=np.arange(10)**3
print(a)
 
print(a[-1])
print(a[-2])
print(a[-5:-2])

[  0   1   8  27  64 125 216 343 512 729]
729
512
[125 216 343]


In [27]:
 
a=np.arange(12).reshape(4,3)**2 
print(a)
 
print(a[-1,]) 
print(a[-1,-1])
print(a[-3:-1,-2:])

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[ 81 100 121]
121
[[16 25]
 [49 64]]


b)Iterating

In [28]:
 
a=np.arange(12).reshape(4,3)**2 # Create an array "a" with square of numbers from 0 to 11.
print(a)
 
for i in a:
    print(i)

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[0 1 4]
[ 9 16 25]
[36 49 64]
[ 81 100 121]


In [29]:
 
for i in a.flat:
    print(i)

0
1
4
9
16
25
36
49
64
81
100
121


###(V)Matrix operations on NumPy arrays.

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [31]:
print(a+b)

[[ 6  8]
 [10 12]]


In [32]:
print(a-b)

[[-4 -4]
 [-4 -4]]


In [33]:
print(a/b)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [34]:
print(a@b)

[[19 22]
 [43 50]]
